package:
  name: conda-build-example
  version: "0.1.0"

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps .

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6

